Repository kyeongmin21/greeny, pull requests merged in 2022-12, with the labels that each got.

#3 feat: [header] 검색모달창 생성
  package-lock.json
  package.json
  public/css/common.css
  public/css/header.css
  public/images/svg/close.svg
  src/components/Header.vue
  src/components/modal/ModalSearch.vue
  src/layouts/HomeLayout.vue
  src/main.js
Labels: feat

#4 Greeny 1
  public/css/common.css
  public/css/header.css
  src/components/modal/ModalSearch.vue
Labels: feat

#6 Greeny 5
  package-lock.json
  package.json
  public/css/common.css
  public/css/footer.css
  public/css/header.css
  public/css/home.css
  public/css/reset.css
  public/images/svg/google.svg
  public/images/svg/kakao.svg
  public/images/svg/naver.svg
  src/components/common/validations/inputbox.vue
  src/layouts/HomeLayout.vue
  src/layouts/NoneLayout.vue
  src/main.js
  src/plugins/bootstrap-vue.js
  src/plugins/vee-validate.js
  src/router/index.js
  src/router/path.my-page.js
  src/views/NotFound.vue
  src/views/challenge/List.vue
  src/views/dailyLook/List.vue
  src/views/event/List.vue
  src/views/magazine/List.vue
  src/views/myPage/Login.vue
Labels: docs, style

#7 Greeny 5
  package-lock.json
  package.json
  public/css/common.css
  public/css/header.css
  public/index.html
  src/views/myPage/Login.vue
Labels: feat

#10 Greeny 9
  public/images/home/home_img01.png
  public/images/home/home_img02.png
  public/images/home/home_img03.png
  public/images/home/home_img04.png
  src/layouts/HomeLayout.vue
  src/layouts/Thelayout.vue
Labels: docs

#18 Greeny 17
  src/layouts/Thelayout.vue
  src/router/index.js
  src/router/path.my-page.js
  src/views/myPage/Join.vue
  src/views/myPage/Login.vue
  src/views/myPage/Main.vue
Labels: feat

#21 Greeny 20
  public/css/challenge.css
  public/css/common.css
  public/css/header.css
  public/images/challenge/challenge_01.jpg
  public/images/challenge/challenge_02.jpg
  public/images/challenge/challenge_03.jpg
  public/images/challenge/challenge_04.jpg
  public/images/challenge/challenge_05.jpg
  public/images/challenge/challenge_06.jpg
  public/images/challenge/challenge_07.jpg
  public/images/challenge/challenge_08.jpg
  public/images/challenge/challenge_09.jpg
  public/images/challenge/challenge_10.jpg
  public/images/challenge/challenge_11.jpg
  public/images/challenge/challenge_12.jpg
  public/images/svg/bookmark.svg
  public/images/svg/symbol.svg
  src/App.vue
  src/assets/css/style.css
  src/components/Category.vue
  src/components/Header.vue
  src/components/HomeHeader.vue
  src/components/Menu.vue
  src/plugins/vee-validate.js
  src/router/index.js
  src/router/path.challenge.js
  src/views/Home.vue
  src/views/challenge/Detail.vue
  src/views/challenge/List.vue
  src/views/myPage/Join.vue
  src/views/myPage/Login.vue
Labels: feat

#23 Greeny 22
  public/css/footer.css
  public/css/header.css
  public/css/home.css
  public/css/reset.css
  public/images/svg/home_title02.png
  public/images/svg/home_title02.svg
  public/images/svg/home_title03.png
  public/images/svg/home_title03.svg
  public/index.html
  src/components/Header.vue
  src/components/Menu.vue
  src/views/Home.vue
Labels: bug, feat

#25 Greeny 24
  package-lock.json
  public/css/home.css
  src/views/Home.vue
Labels: style

#26 fix: brand 부분 반응형으로 구현
  public/css/header.css
  public/css/home.css
  public/images/svg/more_green_full.svg
  public/images/svg/more_green_line.svg
  src/components/Header.vue
  src/views/Home.vue
Labels: style

#29 Greeny 27
  public/css/header.css
  public/css/home.css
  public/images/home/home_img03-1.png
  public/images/home/home_img03.png
  public/images/home/home_img04-1.png
  public/images/home/home_img04.png
  public/images/svg/more_green_full.svg
  src/components/Header.vue
  src/views/Home.vue
Labels: feat

#30 fix: 로그인 페이지 반응형
  public/css/header.css
  public/css/login.css
  src/assets/css/style.css
Labels: style

#32 style: 검색모달창 반응형 구현
  public/css/header.css
  src/components/Header.vue
Labels: feat, style

#39 style: Home 수정
  public/css/home.css
  public/images/svg/best.svg
  public/images/svg/bookmark.svg
  public/images/svg/heart.svg
  src/assets/images/bookmark.svg
  src/assets/images/heart.svg
  src/views/Home.vue
Labels: style
